const C3 = self.C3;
self.C3_GetObjectRefTable = function () {
	return [
		C3.Plugins.Sprite,
		C3.Behaviors.Tween,
		C3.Plugins.AJAX,
		C3.Plugins.Json,
		C3.Plugins.Arr,
		C3.Plugins.Touch,
		C3.Plugins.Timeline,
		C3.Behaviors.MoveTo,
		C3.Behaviors.Fade,
		C3.Plugins.Particles,
		C3.Plugins.TiledBg,
		C3.Behaviors.Rotate,
		C3.Behaviors.Physics,
		C3.Plugins.Spritefont2,
		C3.Plugins.LocalStorage,
		C3.Plugins.Audio,
		C3.Plugins.Text,
		C3.Plugins.System.Cnds.IsGroupActive,
		C3.Plugins.System.Cnds.OnLayoutStart,
		C3.Plugins.Sprite.Acts.Destroy,
		C3.Plugins.System.Acts.SetVar,
		C3.Plugins.Sprite.Exps.Width,
		C3.Plugins.Sprite.Exps.Height,
		C3.Plugins.Sprite.Acts.SetOpacity,
		C3.Plugins.System.Cnds.ForEachOrdered,
		C3.Plugins.Sprite.Exps.Y,
		C3.Plugins.Sprite.Cnds.IsOverlapping,
		C3.Plugins.Sprite.Exps.X,
		C3.Plugins.Sprite.Acts.SetInstanceVar,
		C3.Plugins.System.Cnds.For,
		C3.Plugins.Json.Exps.Get,
		C3.Plugins.System.Cnds.PickByEvaluate,
		C3.Plugins.System.Exps.loopindex,
		C3.Plugins.System.Exps.min,
		C3.Plugins.System.Exps.max,
		C3.Plugins.System.Cnds.EvaluateExpression,
		C3.Plugins.System.Cnds.Else,
		C3.Plugins.System.Acts.StopLoop,
		C3.Plugins.System.Acts.CreateObject,
		C3.Plugins.System.Cnds.PickLastCreated,
		C3.Plugins.Sprite.Acts.SetWidth,
		C3.Plugins.Sprite.Exps.ImagePointX,
		C3.Plugins.Sprite.Acts.SetAngle,
		C3.Plugins.Sprite.Exps.ImagePointY,
		C3.Plugins.Sprite.Acts.SetPos,
		C3.Plugins.Sprite.Acts.SetSize,
		C3.Plugins.Sprite.Acts.AddChild,
		C3.Plugins.System.Acts.Wait,
		C3.Plugins.Sprite.Acts.SetX,
		C3.Plugins.System.Exps.layoutwidth,
		C3.Plugins.Arr.Acts.SetSize,
		C3.Plugins.System.Exps.len,
		C3.Plugins.Arr.Acts.Push,
		C3.Plugins.System.Exps.tokenat,
		C3.Behaviors.Tween.Acts.TweenTwoProperties,
		C3.Plugins.Sprite.Cnds.PickChildren,
		C3.Plugins.System.Cnds.ForEach,
		C3.Plugins.System.Exps.random,
		C3.Plugins.Arr.Exps.Width,
		C3.Plugins.Sprite.Acts.SetAnim,
		C3.Plugins.Arr.Exps.At,
		C3.Plugins.Arr.Acts.Delete,
		C3.Plugins.System.Acts.SetFunctionReturnValue,
		C3.Plugins.Touch.Cnds.OnTouchStart,
		C3.Plugins.Touch.Cnds.IsTouchingObject,
		C3.Plugins.Sprite.Exps.UID,
		C3.Behaviors.Tween.Acts.TweenOneProperty,
		C3.Plugins.Sprite.Exps.Angle,
		C3.Plugins.Touch.Cnds.IsInTouch,
		C3.Plugins.Arr.Exps.IndexOf,
		C3.Plugins.System.Cnds.PickAll,
		C3.Behaviors.Tween.Acts.StopTweens,
		C3.Plugins.Sprite.Exps.AnimationName,
		C3.Plugins.Touch.Exps.X,
		C3.Plugins.Touch.Exps.Y,
		C3.Plugins.Spritefont2.Acts.SetText,
		C3.Plugins.Spritefont2.Exps.TextWidth,
		C3.Plugins.Touch.Cnds.OnTouchEnd,
		C3.Plugins.Audio.Acts.Play,
		C3.Behaviors.MoveTo.Acts.MoveToPosition,
		C3.Behaviors.MoveTo.Acts.SetMaxSpeed,
		C3.Plugins.Timeline.Acts.SetInstance,
		C3.Plugins.Timeline.Acts.PlayTimeline,
		C3.Behaviors.MoveTo.Cnds.OnArrived,
		C3.Plugins.System.Acts.WaitForPreviousActions,
		C3.Plugins.Particles.Acts.SetX,
		C3.Behaviors.Fade.Acts.StartFade,
		C3.Plugins.Sprite.Cnds.OnAnyAnimFinished,
		C3.Plugins.Json.Acts.SetValue,
		C3.Plugins.LocalStorage.Acts.SetItem,
		C3.Plugins.Json.Exps.ToBeautifiedString,
		C3.Plugins.System.Exps.float,
		C3.Plugins.System.Cnds.Repeat,
		C3.Behaviors.Physics.Acts.SetVelocity,
		C3.Behaviors.Physics.Acts.EnableCollisions,
		C3.Plugins.Sprite.Exps.Count,
		C3.Plugins.Audio.Acts.PlayByName,
		C3.Plugins.Touch.Cnds.OnTouchObject,
		C3.Plugins.Sprite.Exps.Opacity,
		C3.Plugins.System.Acts.ResetGlobals,
		C3.Plugins.Json.Exps.ArraySize,
		C3.Plugins.Json.Cnds.ForEach,
		C3.Plugins.System.Exps.layoutname,
		C3.Plugins.Sprite.Acts.SetDefaultColor,
		C3.Plugins.System.Exps.rgba255,
		C3.Plugins.System.Exps.zeropad,
		C3.Plugins.TiledBg.Acts.SetInstanceVar,
		C3.Plugins.TiledBg.Exps.Width,
		C3.Plugins.TiledBg.Acts.SetWidth,
		C3.Plugins.System.Acts.GoToLayout,
		C3.Plugins.AJAX.Acts.Request,
		C3.Plugins.AJAX.Cnds.OnComplete,
		C3.Plugins.AJAX.Exps.LastData,
		C3.ScriptsInEvents.Uievent_Event71_Act1,
		C3.Plugins.Json.Acts.Parse,
		C3.Plugins.System.Acts.GoToLayoutByName,
		C3.Plugins.System.Exps.layoutheight,
		C3.Plugins.Sprite.Acts.MoveToLayer,
		C3.Plugins.Spritefont2.Acts.MoveToLayer,
		C3.Plugins.TiledBg.Exps.X,
		C3.Plugins.TiledBg.Exps.Y,
		C3.Plugins.Audio.Acts.SetSilent,
		C3.Plugins.Audio.Cnds.IsSilent,
		C3.Plugins.System.Cnds.EveryTick,
		C3.Plugins.System.Exps.dt,
		C3.Behaviors.Physics.Acts.SetEnabled,
		C3.Plugins.LocalStorage.Acts.CheckItemExists,
		C3.Plugins.Audio.Cnds.IsTagPlaying,
		C3.Plugins.LocalStorage.Cnds.OnItemExists,
		C3.Plugins.LocalStorage.Acts.GetItem,
		C3.Plugins.LocalStorage.Cnds.OnItemGet,
		C3.Plugins.LocalStorage.Exps.ItemValue,
		C3.Plugins.LocalStorage.Cnds.OnItemMissing,
		C3.Plugins.AJAX.Acts.RequestFile
	];
};
self.C3_JsPropNameTable = [
	{BG: 0},
	{row: 0},
	{col: 0},
	{letter: 0},
	{is_used: 0},
	{is_destroy: 0},
	{cell: 0},
	{OE73TC: 0},
	{Tween: 0},
	{board_txt_letter: 0},
	{board: 0},
	{Coinbar: 0},
	{letter_grid: 0},
	{board_set: 0},
	{cell_check_rowAndCol: 0},
	{AJAX: 0},
	{JSON_Levels: 0},
	{grid_align: 0},
	{word: 0},
	{is_complete: 0},
	{word_connect: 0},
	{Array_Random: 0},
	{Touch: 0},
	{Array_LetterSelect: 0},
	{is_drawing: 0},
	{uid_letter: 0},
	{Line: 0},
	{TimelineController: 0},
	{uid_cell: 0},
	{MoveTo: 0},
	{Fade: 0},
	{garden_hose: 0},
	{Sprite: 0},
	{watter_effect: 0},
	{scale_timeline: 0},
	{fx_destroy_rice: 0},
	{rotate_timeline: 0},
	{Home_Bg: 0},
	{is_template: 0},
	{page: 0},
	{card_item: 0},
	{card_pics_bg: 0},
	{card_btn: 0},
	{card_bar_bg: 0},
	{step_width: 0},
	{full_width: 0},
	{card_bar: 0},
	{home_logo: 0},
	{boxde: 0},
	{coin_extra: 0},
	{card_ic_coins: 0},
	{card_ic_leaf: 0},
	{word_btn_hint: 0},
	{coin_booster: 0},
	{btn__setting: 0},
	{btn_shufte: 0},
	{bg_controller: 0},
	{settings_controller: 0},
	{settings_btn_audio: 0},
	{settings_btn_home: 0},
	{settings_btn_continue: 0},
	{card_ic_lock: 0},
	{Rotate: 0},
	{rays: 0},
	{card_banner: 0},
	{card_btn_close: 0},
	{Physics: 0},
	{fruits: 0},
	{card_title: 0},
	{card_txt_level: 0},
	{coin_txt: 0},
	{btn_next: 0},
	{card_bg_btn: 0},
	{rightarrow: 0},
	{direction: 0},
	{active: 0},
	{card_btn_page: 0},
	{JSON_Config: 0},
	{LocalStorage: 0},
	{card_ic_complete: 0},
	{level_txt: 0},
	{booster_cost_txt: 0},
	{Audio: 0},
	{setting_btn_close: 0},
	{time_delay: 0},
	{coin_bonus: 0},
	{round_bg_content: 0},
	{bg_content: 0},
	{letter_txt_selected: 0},
	{JSON_Chapters: 0},
	{Text: 0},
	{word_isTouch: 0},
	{word_selectedLetters: 0},
	{word_uidSelectLeter: 0},
	{word_indexAudio: 0},
	{word_uidSelected: 0},
	{word_isComplete: 0},
	{gardenHose_width: 0},
	{gardenHose_height: 0},
	{word_isCheck: 0},
	{align_x_min: 0},
	{align_x_max: 0},
	{align_y_min: 0},
	{align_y_max: 0},
	{count: 0},
	{word_data: 0},
	{index: 0},
	{x_line_start: 0},
	{y_line_start: 0},
	{value: 0},
	{size: 0},
	{x: 0},
	{y: 0},
	{UI_stateLocked: 0},
	{card_x: 0},
	{card_y: 0},
	{card_chapter: 0},
	{complete_isBonus: 0},
	{chapter: 0},
	{chapter_unlock: 0},
	{chapter_end: 0},
	{level_unlock: 0},
	{fruit_key: 0},
	{result: 0},
	{is_chapter_next: 0},
	{bonus: 0},
	{layer_name: 0},
	{nums: 0},
	{game_levelUnlock: 0},
	{key_main: 0}
];

self.InstanceType = {
	BG: class extends self.ISpriteInstance {},
	cell: class extends self.ISpriteInstance {},
	OE73TC: class extends self.ISpriteInstance {},
	board_txt_letter: class extends self.ISpriteInstance {},
	board: class extends self.ISpriteInstance {},
	Coinbar: class extends self.ISpriteInstance {},
	letter_grid: class extends self.ISpriteInstance {},
	board_set: class extends self.ISpriteInstance {},
	cell_check_rowAndCol: class extends self.ISpriteInstance {},
	AJAX: class extends self.IInstance {},
	JSON_Levels: class extends self.IJSONInstance {},
	grid_align: class extends self.ISpriteInstance {},
	word_connect: class extends self.ISpriteInstance {},
	Array_Random: class extends self.IArrayInstance {},
	Touch: class extends self.IInstance {},
	Array_LetterSelect: class extends self.IArrayInstance {},
	Line: class extends self.ISpriteInstance {},
	TimelineController: class extends self.IInstance {},
	garden_hose: class extends self.ISpriteInstance {},
	Sprite: class extends self.ISpriteInstance {},
	watter_effect: class extends self.IParticlesInstance {},
	scale_timeline: class extends self.ISpriteInstance {},
	fx_destroy_rice: class extends self.ISpriteInstance {},
	rotate_timeline: class extends self.ISpriteInstance {},
	Home_Bg: class extends self.ISpriteInstance {},
	card_item: class extends self.ISpriteInstance {},
	card_pics_bg: class extends self.ISpriteInstance {},
	card_btn: class extends self.ISpriteInstance {},
	card_bar_bg: class extends self.ISpriteInstance {},
	card_bar: class extends self.ITiledBackgroundInstance {},
	home_logo: class extends self.ISpriteInstance {},
	boxde: class extends self.ISpriteInstance {},
	coin_extra: class extends self.ISpriteInstance {},
	card_ic_coins: class extends self.ISpriteInstance {},
	card_ic_leaf: class extends self.ISpriteInstance {},
	word_btn_hint: class extends self.ISpriteInstance {},
	coin_booster: class extends self.ISpriteInstance {},
	btn__setting: class extends self.ISpriteInstance {},
	btn_shufte: class extends self.ISpriteInstance {},
	bg_controller: class extends self.ISpriteInstance {},
	settings_controller: class extends self.ISpriteInstance {},
	settings_btn_audio: class extends self.ISpriteInstance {},
	settings_btn_home: class extends self.ISpriteInstance {},
	settings_btn_continue: class extends self.ISpriteInstance {},
	card_ic_lock: class extends self.ISpriteInstance {},
	rays: class extends self.ISpriteInstance {},
	card_banner: class extends self.ISpriteInstance {},
	card_btn_close: class extends self.ISpriteInstance {},
	fruits: class extends self.ISpriteInstance {},
	card_title: class extends self.ISpriteFontInstance {},
	card_txt_level: class extends self.ISpriteFontInstance {},
	coin_txt: class extends self.ISpriteFontInstance {},
	btn_next: class extends self.ISpriteInstance {},
	card_bg_btn: class extends self.ISpriteInstance {},
	rightarrow: class extends self.ISpriteInstance {},
	card_btn_page: class extends self.ISpriteInstance {},
	JSON_Config: class extends self.IJSONInstance {},
	LocalStorage: class extends self.IInstance {},
	card_ic_complete: class extends self.ISpriteInstance {},
	level_txt: class extends self.ISpriteFontInstance {},
	booster_cost_txt: class extends self.ISpriteFontInstance {},
	Audio: class extends self.IInstance {},
	setting_btn_close: class extends self.ISpriteInstance {},
	coin_bonus: class extends self.ISpriteInstance {},
	round_bg_content: class extends self.ISpriteInstance {},
	bg_content: class extends self.ISpriteInstance {},
	letter_txt_selected: class extends self.ISpriteFontInstance {},
	JSON_Chapters: class extends self.IJSONInstance {},
	Text: class extends self.ITextInstance {}
}